DROP TABLE IF EXISTS Component;
  
CREATE TABLE Component (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  category VARCHAR(250) NOT NULL,
  posX INTEGER NOT NULL,
  posY INTEGER NOT NULL,
  posZ INTEGER NOT NULL,
  inspectiondate DATE NOT NULL,
  price DOUBLE DEFAULT NULL
);

DROP TABLE IF EXISTS Item;
  
CREATE TABLE Item (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  category VARCHAR(250) NOT NULL,
  posX INTEGER NOT NULL,
  posY INTEGER NOT NULL,
  posZ INTEGER NOT NULL,
  inspectiondate DATE NOT NULL,
  price DOUBLE DEFAULT NULL
);